### PR TITLE
update libraries

### PR DESCRIPTION
**Pull request by ljuster**
### package.json and yarn.lock now reflect most updated version of   
    - `bs-platform`
    - `react-on-rails`
    - `reason-react`

### CODE REVIEW

**Comment by justin808** [comment]
@ljuster did you look at the CI failure?

**Comment by ljuster** [comment]
> @ljuster did you look at the CI failure?
@justin808 
Yes, same issue as i was having adding reason to `react_on_rails` dummy app, looking into it.

**Comment by ljuster** [comment]
@justin808 @alexfedoseev I used [your reason react example](https://github.com/shakacode/reason-react-on-rails-example) with updated libraries linking to my local updated copy of `bs-react-on-rails` to make sure things worked with `string` instead of `stringToElement`

**Comment by ljuster** [comment]
> It looks good. Prolly, makes sense to switch to hooks/JSX@3 since it's bumped to `0.7.0`. Not critical tho.

@alexfedoseev not sure what that switch entails....just a config setting and/or package update?

**Comment by alexfedoseev** [comment]
>@alexfedoseev not sure what that switch entails....just a config setting and/or package update?

@ljuster In context of this PR, a bit more: you'd need to change also a `Page` component in examples to the new way of defining components (see updated [documentation of `reason-react`](https://reasonml.github.io/reason-react/docs/en/components)).

**Comment by kchivorn** [comment]
Hi @justin808, will this pull request get merged? I want to use this in my project. The old one does not work with this example https://github.com/shakacode/rescript-react-on-rails-example

**Comment by justin808** [comment]
@alexfedoseev can you review and release?

**Comment by alexfedoseev** [comment]
It was addressed in #4. Thanks @ ljuster!

**Pull request closed without merging**
